// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1PF8SZYYq1a_qxJFNX69-mUNQib5ZZWY',
    appId: '1:149089013008:web:f430e66c1857a347e56995',
    messagingSenderId: '149089013008',
    projectId: 'fir-login-out',
    authDomain: 'fir-login-out.firebaseapp.com',
    storageBucket: 'fir-login-out.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmkRsQExbyKpUpjXeU3K46qwquOFwnrrQ',
    appId: '1:149089013008:android:9dee9b44a99a2243e56995',
    messagingSenderId: '149089013008',
    projectId: 'fir-login-out',
    storageBucket: 'fir-login-out.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBSkUVI4gCvxjm0LBhiOH85xDVNSw_Z0o',
    appId: '1:149089013008:ios:fd0b9f1e1df1ac6fe56995',
    messagingSenderId: '149089013008',
    projectId: 'fir-login-out',
    storageBucket: 'fir-login-out.appspot.com',
    iosBundleId: 'com.example.firebaseLoginoutAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBSkUVI4gCvxjm0LBhiOH85xDVNSw_Z0o',
    appId: '1:149089013008:ios:f7601b5da6ac22bae56995',
    messagingSenderId: '149089013008',
    projectId: 'fir-login-out',
    storageBucket: 'fir-login-out.appspot.com',
    iosBundleId: 'com.example.firebaseLoginoutAuth.RunnerTests',
  );
}
